### ISSUE TITLE
bap command not working/ alternatives

### ISSUE THREAD

**Issue by Ruturaj4** [BinaryAnalysisPlatform/bap#1190]
I am using bap to run following project: [debin](https://github.com/eth-sri/debin)

They don't specify what version of bap they use. I used latest version (built using opam) to run their project. But it gives me following error:

```
bap: unknown option `--symbolizer'.
Usage: bap disassemble [OPTION]... [FILE]
Try `bap disassemble --help' or `bap --help' for more information.
Traceback (most recent call last):
  File "py/predict.py", line 87, in <module>
    main()
  File "py/predict.py", line 73, in main
    b = Binary(config, elffile)
  File "/mnt/d/Ruturaj/binary_research/debin/debin/py/binary.py", line 90, in __init__
    bap_json = json.loads(bap_result)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I observed that they are using following commands in their code:

```
if self.config.BAP_FILE_PATH == '' or not os.path.exists(self.config.BAP_FILE_PATH):
            if self.config.BYTEWEIGHT_SIGS_PATH == '':
                if self.sections.has_sec(SYMTAB):
                    bap_result = subprocess.getoutput('bap {} --pass=loc --symbolizer=objdump --rooter=internal'.format(self.path))
                else:
                    bap_result = subprocess.getoutput('bap {} --pass=loc --symbolizer=objdump'.format(self.path))
            else:
                bap_result = subprocess.getoutput('bap {} --pass=loc --symbolizer=objdump --byteweight-sigs={}'.format(self.path, self.config.BYTEWEIGHT_SIGS_PATH))
            bap_json = json.loads(bap_result)
        else:
            bap_json = json.load(open(self.config.BAP_FILE_PATH))
```

I can't run these commands, for e.g. flags like --symbolizer and --rooter are absent in the current version of bap.

I would like to know if there any way to fix this. i.e. if there's any other way to reproduce the similar output, what otherwise produced by these flags.

I find the following manual - https://binaryanalysisplatform.github.io/bap/api/v1.5.0/man1/bap.1.html, where these flags are specified. But, I think this is a much older version.

Thanks in advanced.

**Comment by XVilka** [comment]
They use 1.4.0: https://github.com/eth-sri/debin/blob/master/dockerfile#L37

Current BAP version is 2.1.0 and A LOT has changed.

**Comment by Ruturaj4** [comment]
I actually figured it out, but thanks anyways.
