### ISSUE TITLE
use from  python 

### ISSUE THREAD

**Issue by Icefroge** [BinaryAnalysisPlatform/bap#184]
when i  use   print '\n'.join(insn.asm for insn in bap.disasm("\x48\x83\xec\x08"))  in  python 2.7:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bap.py", line 87, in disasm
    return run(load_chunk(obj, **kwargs))
  File "bap.py", line 96, in load_chunk
    return get_instance(**kwargs).load_chunk(s, **kwargs)
  File "bap.py", line 53, in get_instance
    storage.instance = Bap(args)
  File "bap.py", line 242, in __init__
    self.__dict__.update(spawn_server(**server))
  File "bap.py", line 67, in spawn_server
    process = Popen([name, '--port=' + port])
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ivg** [comment]
either you didn't install bap, or it is not on your path. You should be able to run `bap-server`. Don't forget that this is only bindings
